name: 'Blog Queue Workflow'
author: 'matthewjdegarmo'
description: 'Publish blog posts from a queue of posts based on a schedule.'
branding:
  icon: archive
  color: purple

inputs:
  queue_path:
    description: 'Path to the queue directory where pending posts are stored.'
    required: true
  destination_path:
    description: 'Path to the published posts directory for your blog.'
    required: true
  committer_username:
    description: "Username used while committing to the repo"
    default: "BLogQueue-post-bot"
    required: false
  committer_email:
    description: "Email id used while committing to the repo"
    default: "BlogQueue-post-bot@matthewjdegarmo.com"
    required: false

runs:
  using: composite
  steps:
    - run: >
        ${{ github.action_path }}/action.ps1
        -Path        "${{ inputs.queue_path }}"
        -Destination "${{ inputs.destination_path }}"
        -CommitterUsername "${{ inputs.committer_username }}"
        -CommitterEmail    "${{ inputs.committer_email }}"
      shell: pwsh
